[package]
name = "graphql_semantic_compare"
version.workspace = true
authors.workspace = true
edition = "2021"
license.workspace = true
publish.workspace = true
repository.workspace = true
description = "Semantic comparing for GraphQL documents built on top of `apollo_parser::Lexer`"

[dependencies]
apollo-parser = "0.8"
itertools = "0.14"
textwrap = "0.16"
